//go:build zknative

package zknative

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/SUNET/vc/pkg/mdoc/zkcircuit"
)

// This test is a REAL end-to-end exercise of the cgo boundary: it fetches
// the actual V8/2-attribute circuit from the live, deployed zk-circuits
// catalog service (https://zk-circuits.fly.dev) and verifies a REAL,
// known-good Longfellow V8 pairwise-pseudonym (PPID) proof against it -
// mirroring zk-cred-longfellow's own go-cabi-smoketest program.
//
// The proof + supporting fixtures (pkg/mdoc/testdata/zk_native/*) were
// generated by zk-cred-longfellow's own, already-tested prover
// (mdoc_zk::prover_v8_test's GARY_MDOC_HEX fixture) and dumped via:
//
//	cargo test --release go_ffi::tests::dump_golden_fixture_for_go_smoke_test -- --ignored
//
// (see that crate's src/go_ffi.rs test module). The circuit itself is
// NOT vendored here (it's ~104MB decompressed) - it's fetched fresh from
// the live catalog service every run, decompressed, and its SHA-256
// verified against the catalog's own declared hash before use, exactly as
// pkg/mdoc/zk_native_cgo.go's real call path does.
//
// Requires network access to zk-circuits.fly.dev; skipped automatically if
// that's unreachable (e.g. an offline CI runner) rather than failing the
// whole suite.
func TestVerifyWithPPID_RealLiveCircuitAndGoldenProof(t *testing.T) {
	circuit, version, numAttrs := fetchLiveTestCircuit(t)
	fixtures := loadFixtures(t)

	verifier, err := NewVerifier(circuit, version, numAttrs)
	if err != nil {
		t.Fatalf("NewVerifier: %v", err)
	}
	defer verifier.Close()

	args := VerifyWithPPIDArgs{
		IssuerPublicKeySEC1: fixtures.issuerPK,
		Attributes: []Attribute{
			{Identifier: "given_name", ValueCBOR: fixtures.givenNameCBOR},
			{Identifier: "pairwise_pseudonym", ValueCBOR: fixtures.ppidCBOR},
		},
		DocType:               fixtures.docType,
		DeviceNameSpacesBytes: []byte{0xa0}, // empty CBOR map
		SessionTranscript:     fixtures.transcript,
		Time:                  fixtures.time,
		VerifierContext:       fixtures.verifierContext,
		Proof:                 fixtures.proof,
	}

	// 1. The genuine proof must verify successfully.
	if err := verifier.VerifyWithPPID(args); err != nil {
		t.Fatalf("expected genuine proof to verify, got error: %v", err)
	}

	// 2. The same handle must be reusable for a second call (circuit
	// loading is meant to be cached and reused, not repeated per call).
	if err := verifier.VerifyWithPPID(args); err != nil {
		t.Fatalf("expected second verify with the same handle to succeed, got: %v", err)
	}

	// 3. A tampered proof (flip one byte) must be rejected with a real
	// error.
	tampered := append([]byte(nil), fixtures.proof...)
	tampered[len(tampered)-1] ^= 0xff
	tamperedArgs := args
	tamperedArgs.Proof = tampered
	err = verifier.VerifyWithPPID(tamperedArgs)
	if err == nil {
		t.Fatal("expected tampered proof to be rejected")
	}
	if !strings.Contains(err.Error(), "rust_verify_with_ppid") {
		t.Errorf("expected error to reference the native call, got: %v", err)
	}

	// 4. Wrong attribute count must be rejected cleanly, not panic.
	wrongAttrsArgs := args
	wrongAttrsArgs.Attributes = args.Attributes[:1]
	if err := verifier.VerifyWithPPID(wrongAttrsArgs); err == nil {
		t.Error("expected wrong attribute count to be rejected")
	}

	// 5. Wrong verifier_context length must be rejected cleanly.
	shortCtxArgs := args
	shortCtxArgs.VerifierContext = args.VerifierContext[:16]
	if err := verifier.VerifyWithPPID(shortCtxArgs); err == nil {
		t.Error("expected short verifier_context to be rejected")
	}
}

// fetchLiveTestCircuit fetches the same real V8/2-attribute circuit used by
// TestVerifyWithPPID_RealLiveCircuitAndGoldenProof from the live catalog
// service, skipping the calling test (not failing it) if the service is
// unreachable.
func fetchLiveTestCircuit(t *testing.T) (circuit []byte, version, numAttrs uint8) {
	t.Helper()
	const circuitID = "longfellow-libzk-v1_8_2_4307_2945"

	client := zkcircuit.NewClient()
	ctx := context.Background()

	descriptor, err := client.FetchCircuit(ctx, circuitID)
	if err != nil {
		t.Skipf("zk-circuits.fly.dev unreachable or circuit missing, skipping live test: %v", err)
	}
	v, ok := descriptor.ParamInt("version")
	if !ok || v != 8 {
		t.Fatalf("expected circuit %s to report version=8, got %d (ok=%v)", circuitID, v, ok)
	}
	n, ok := descriptor.ParamInt("num_attributes")
	if !ok || n != 2 {
		t.Fatalf("expected circuit %s to report num_attributes=2, got %d (ok=%v)", circuitID, n, ok)
	}

	circuitBytes, err := client.DownloadAndDecompress(ctx, descriptor)
	if err != nil {
		if strings.Contains(err.Error(), "failed to download a hash-verified artifact") {
			t.Skipf("zk-circuits.fly.dev unreachable, skipping live test: %v", err)
		}
		t.Fatalf("DownloadAndDecompress: %v", err)
	}
	return circuitBytes, uint8(v), uint8(n)
}

// TestVerifier_Close_ConcurrentCallsSafe is a regression test for the
// check-then-act double-free race masv3971 flagged on PR #576: the old
// Close() checked v.handle == nil and freed/nilled it without any
// synchronization, so two goroutines racing Close() on the same live handle
// could both pass the nil check and both call rust_free_verifier - a cgo
// double-free (crash or heap corruption under a real allocator, not just a
// leak). With the sync.Once guard, only one of N concurrent Close() calls
// actually frees the handle; this test only proves that concurrent Close()
// doesn't crash/corrupt - it can't itself detect a double-free that the
// allocator happens not to crash on, which is exactly why the race was worth
// fixing structurally rather than trusting a test to catch it.
func TestVerifier_Close_ConcurrentCallsSafe(t *testing.T) {
	circuit, version, numAttrs := fetchLiveTestCircuit(t)

	verifier, err := NewVerifier(circuit, version, numAttrs)
	if err != nil {
		t.Fatalf("NewVerifier: %v", err)
	}

	const goroutines = 16
	var wg sync.WaitGroup
	wg.Add(goroutines)
	for range goroutines {
		go func() {
			defer wg.Done()
			if err := verifier.Close(); err != nil {
				t.Errorf("Close: %v", err)
			}
		}()
	}
	wg.Wait()

	// A further call, after every concurrent one has returned, must still
	// be a harmless no-op.
	if err := verifier.Close(); err != nil {
		t.Errorf("Close after concurrent Close calls: %v", err)
	}
}

// TestNewVerifier_RejectsEmptyCircuit confirms empty input is rejected
// before ever crossing into cgo/Rust.
func TestNewVerifier_RejectsEmptyCircuit(t *testing.T) {
	if _, err := NewVerifier(nil, 8, 2); err == nil {
		t.Fatal("expected an error for an empty circuit")
	}
}

// TestNewVerifier_RejectsUnsupportedVersion confirms a version outside
// {6,7,8} is rejected by the native side with a clear error, not a crash.
func TestNewVerifier_RejectsUnsupportedVersion(t *testing.T) {
	// A tiny non-empty but bogus "circuit" is enough to exercise the
	// version-validation path, which happens before any real circuit
	// parsing.
	_, err := NewVerifier([]byte{0x00}, 9, 2)
	if err == nil {
		t.Fatal("expected an error for an unsupported circuit_version")
	}
}

type goldenFixtures struct {
	issuerPK        []byte
	givenNameCBOR   []byte
	ppidCBOR        []byte
	transcript      []byte
	verifierContext []byte
	proof           []byte
	docType         string
	time            string
}

func loadFixtures(t *testing.T) goldenFixtures {
	t.Helper()
	dir := filepath.Join("..", "testdata", "zk_native")
	read := func(name string) []byte {
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("reading fixture %s: %v", name, err)
		}
		return data
	}
	return goldenFixtures{
		issuerPK:        read("issuer_pk.bin"),
		givenNameCBOR:   read("given_name_cbor.bin"),
		ppidCBOR:        read("ppid_cbor.bin"),
		transcript:      read("transcript.bin"),
		verifierContext: read("verifier_context.bin"),
		proof:           read("proof.bin"),
		docType:         strings.TrimSpace(string(read("doc_type.txt"))),
		time:            strings.TrimSpace(string(read("time.txt"))),
	}
}
