---
common:
  mongo:
    uri: mongodb://mongo:27017
  production: false
  tracing:
    addr: jaeger:4318
    type: jaeger
  queues:
    simple_queue:
      vc_persistent_save:
        name: vc_persistent_save
      vc_persistent_get:
        name: vc_persistent_get
      vc_persistent_delete:
        name: vc_persistent_delete
      vc_persistent_replace:
        name: vc_persistent_replace
  key_value:
    db: 3
    addr: redis:6379
    password: test-password
  qr:
    base_url: "https://deutsche-rentenversicherung.de"
    recovery_level: 2
    size: 256

issuer:
  api_server:
    addr: :8080
  grpc_server:
    addr: vc_dev_issuer:8090
  datastore:
    addr: datastore:8080
  
datastore:
  api_server:
    addr: :8080
  grpc_server:
    addr: vc_dev_datastore:8090
  
verifier:
  api_server:
    addr: :8080
  grpc_server:
    addr: vc_dev_verifier:8090

registry:
  api_server:
    addr: :8080
  smt:
    update_periodicity: 5
    init_leaf: 575cea4a-5725-11ee-8287-2b486b7ace28
  grpc_server:
    addr: vc_dev_registry:8090

persistent:
  api_server:
    addr: :8080

apigw:
  api_server:
    addr: :8080

mock_as:
  api_server:
    addr: :8080
  datastore_url: http://vc_dev_apigw:8080
