---
version: "3"

services:
  issuer:
    container_name: "vc_issuer"
    image: vc_issuer:latest
    volumes:
      - ./cert:/cert:ro
      - ./dev_config_docker.yaml:/config.yaml:ro
    depends_on:
      - redis
      - mongo
    networks:
      vc-net:
        ipv4_address: 172.16.50.2
    environment:
      - "VC_CONFIG_YAML=config.yaml"

  verifier:
    container_name: "vc_verifier"
    image: vc_verifier:latest
    volumes:
      - ./cert:/cert:ro
      - ./dev_config_docker.yaml:/config.yaml:ro
    depends_on:
      - redis
      - mongo
      - issuer
    networks:
      vc-net:
        ipv4_address: 172.16.50.3
    environment:
      - "VC_CONFIG_YAML=config.yaml"

  redis:
    image: redis:alpine
    container_name: "vc_redis"
    expose:
      - 6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      vc-net:
        ipv4_address: 172.16.50.4
    
  mongo:
    image: mongo:4.0.10
    container_name: "vc_mongo"
    expose:
      - 27017
    volumes:
      - mongo_data:/data
    networks:
      vc-net:
        ipv4_address: 172.16.50.6

  ca:
    container_name: "vc_ca"
    image: mockca:latest
    depends_on:
      - redis
      - mongo
      - issuer
      - verifier
    networks:
      vc-net:
        ipv4_address: 172.16.50.7
    environment:
      - "CA_SLEEP=3"

networks:
  vc-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-vc
    ipam:
      driver: default
      config:
        - subnet: 172.16.50.0/24
volumes:
  redis_data:
  mongo_data:
