name: test-golang
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true

      - name: Clone Missing Dependency
        run: |
          git clone https://github.com/google/longfellow-zk.git /tmp/longfellow-zk
          cd /tmp/longfellow-zk
          git checkout 66fab34ac83bdb669be35ca380e16191468e96d4

      - name: Sync dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Run tests
        run: make test