name: test-golang

on: [push, pull_request]

jobs:
  uses: ./.github/workflows/common.yaml@masv_pipeline

  steps:
    - name: Build
      run: |
        make build

    - name: Run tests
      run: |
        make test