name: test-golang
on: [push, pull_request]

jobs:

    steps:


jobs:
  checkout_and_install_go:
    runs-on: ubuntu-latest
  test:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run tests
        run: |
          make test